import type { PerguntaQuiz } from '../../../../tipos';

/**
 * Perguntas de categoria 'revisao' do quiz de Filosofia Jurídica, 1a unidade:
 * as 20 afirmações de verdadeiro ou falso do simulado de fixação do
 * professor, na ordem original. O gabarito e as justificativas seguem os do
 * professor, reescritos com clareza. Todas trazem origem 'professor' (selo
 * "Revisão do professor") e nenhuma carrega gabaritoDoCaderno.
 */
export const revisao: readonly PerguntaQuiz[] = [
    { id: 1, tipo: 'verdadeiro-ou-falso', origem: 'professor', categoria: 'revisao', enunciadoHtml: `Para Platão, a justiça consiste em assegurar que os amigos sejam recompensados e os inimigos punidos, visto que a reparação retributiva do dano é a finalidade precípua do ordenamento jurídico da pólis.`, correta: false, fonteExtra: false, explicacaoHtml: `Platão desconstrói a tese do senso comum grego de fazer o bem aos amigos e o mal aos inimigos. Como a justiça é uma virtude que visa ao aperfeiçoamento da alma, ela jamais pode causar dano nem produzir o mal a quem quer que seja: prejudicar alguém degrada moralmente o indivíduo e retira-lhe a perfeição. É um ponto recorrente em provas.` },

    { id: 2, tipo: 'verdadeiro-ou-falso', origem: 'professor', categoria: 'revisao', enunciadoHtml: `Na tragédia Antígona, de Sófocles, o conflito central ilustra a tensão clássica entre as leis positivas editadas pelo governante da cidade e as leis não escritas de ordem sagrada e natural.`, correta: true, fonteExtra: false, explicacaoHtml: `A dramaturgia de Sófocles retrata o choque emblemático entre o direito positivo, o decreto do rei Creonte, e uma espécie de jusnaturalismo primitivo: as leis não escritas, divinas, perenes e universais, que Antígona invoca para sepultar o irmão.` },

    { id: 3, tipo: 'verdadeiro-ou-falso', origem: 'professor', categoria: 'revisao', enunciadoHtml: `Aristóteles define a justiça corretiva (ou comutativa) como aquela que disciplina a partilha proporcional de honrarias e bens públicos pelo Estado aos cidadãos segundo o mérito individual.`, correta: false, fonteExtra: false, explicacaoHtml: `A partilha proporcional de bens e honrarias segundo o mérito, pela igualdade geométrica, é própria da justiça distributiva. A justiça corretiva (ou comutativa) rege as transações e os contratos entre particulares, sob a regra da igualdade aritmética, a simples.` },

    { id: 4, tipo: 'verdadeiro-ou-falso', origem: 'professor', categoria: 'revisao', enunciadoHtml: `Na teoria platônica descrita em A República, a justiça estatal é concebida como uma virtude harmônica, atingida quando sábios governam, guerreiros defendem e artífices produzem, sem desvios ou interferências recíprocas de suas funções.`, correta: true, fonteExtra: false, explicacaoHtml: `A justiça orgânica de Platão está na harmonia funcional da pólis: os sábios pensam e governam, os guerreiros usam a coragem para defender e os artífices trabalham na produção e na subsistência. A injustiça é o rompimento dessa repartição de papéis.` },

    { id: 5, tipo: 'verdadeiro-ou-falso', origem: 'professor', categoria: 'revisao', enunciadoHtml: `O sofista Protágoras formulou a tese de que a justiça nada mais é do que a conveniência e o interesse do mais forte, convertendo o direito num artifício de pura dominação política.`, correta: false, fonteExtra: false, explicacaoHtml: `A tese de que a justiça é a conveniência do mais forte, que antecipa o positivismo e o relativismo, é de Trasímaco. A contribuição célebre de Protágoras é o homo mensura: "o homem é a medida de todas as coisas", ou seja, cada sujeito julga segundo as suas circunstâncias.` },

    { id: 6, tipo: 'verdadeiro-ou-falso', origem: 'professor', categoria: 'revisao', enunciadoHtml: `A célebre máxima de Rui Barbosa sobre tratar com desigualdade os desiguais, na medida em que se desigualam, baseia-se diretamente no conceito aristotélico de justiça distributiva e igualdade proporcional.`, correta: true, fonteExtra: false, explicacaoHtml: `A máxima vem da formulação aristotélica da justiça distributiva: a igualdade verdadeira é proporcional (geométrica), e por isso se trata igualmente os iguais e desigualmente os desiguais, na medida da desigualdade entre eles.` },

    { id: 7, tipo: 'verdadeiro-ou-falso', origem: 'professor', categoria: 'revisao', enunciadoHtml: `Sócrates admitiu a proposta de fuga apresentada por Críton por entender que a sua condenação, sendo materialmente injusta, autorizava o cidadão a descumprir as sentenças judiciais da pólis.`, correta: false, fonteExtra: false, explicacaoHtml: `Sócrates recusou a fuga. Para ele, o bom cidadão deve obediência às leis da pólis, mesmo diante de uma condenação injusta, para não enfraquecer a autoridade da lei nem encorajar os perversos a violar as leis boas. A injustiça material da sentença não o autorizava a descumpri-la.` },

    { id: 8, tipo: 'verdadeiro-ou-falso', origem: 'professor', categoria: 'revisao', enunciadoHtml: `Para Aristóteles, o critério determinante para classificar um regime político como legítimo ou corrompido não é o número de pessoas no poder, mas a finalidade ética do governo: a busca pelo bem comum ou pelos interesses particulares dos governantes.`, correta: true, fonteExtra: false, explicacaoHtml: `Em A Política, o que separa o regime bom do ruim é a finalidade ética. Governar para o bem comum dá monarquia, aristocracia e república. Governar para interesses egoístas dá tirania, oligarquia e democracia. A quantidade de governantes (um, poucos ou muitos) não é o critério.` },

    { id: 9, tipo: 'verdadeiro-ou-falso', origem: 'professor', categoria: 'revisao', enunciadoHtml: `Na Escolástica de Santo Tomás de Aquino, a Lei Natural identifica-se com os decretos arbitrários do soberano temporal para organizar o comércio e a convivência secular.`, correta: false, fonteExtra: false, explicacaoHtml: `Em Tomás de Aquino, a lei natural é a participação racional da criatura na lei eterna de Deus, e orienta, por exemplo, a conservar a vida, gerar e educar os filhos e buscar a verdade. Os decretos das autoridades humanas pertencem à lei humana, a lei posta ou positiva.` },

    { id: 10, tipo: 'verdadeiro-ou-falso', origem: 'professor', categoria: 'revisao', enunciadoHtml: `A equidade, segundo a tradição aristotélica, opera como um corretivo destinado a flexibilizar e adaptar a norma geral e abstrata às peculiaridades e contingências do caso concreto.`, correta: true, fonteExtra: false, explicacaoHtml: `Como a lei escrita é geral e abstrata, aplicada de modo mecânico ela pode gerar injustiça no caso concreto. A equidade é o corretivo que adapta a norma às circunstâncias reais e assegura o justo meio naquele caso.` },

    { id: 11, tipo: 'verdadeiro-ou-falso', origem: 'professor', categoria: 'revisao', enunciadoHtml: `Santo Agostinho defende, em sua obra A Cidade de Deus, que nos eventuais conflitos entre a lei positiva humana e a lei eterna de Deus, a autoridade civil do Estado deve prevalecer em razão da preservação da paz mundana.`, correta: false, fonteExtra: false, explicacaoHtml: `Agostinho sustenta um jusnaturalismo de caráter teológico. No choque entre a lei dos homens, imperfeita e sujeita a vícios (Cidade dos Homens), e a lei de Deus, perfeita e imutável (Cidade de Deus), deve prevalecer a lei de Deus.` },

    { id: 12, tipo: 'verdadeiro-ou-falso', origem: 'professor', categoria: 'revisao', enunciadoHtml: `Na reflexão platônica sobre a virtude, o ato de cometer injustiça ou infligir o mal a alguém degrada o próprio agente e retira-lhe a perfeição moral, razão pela qual a justiça jamais pode produzir o mal.`, correta: true, fonteExtra: false, explicacaoHtml: `Para Platão, a justiça está ligada à sabedoria da alma e ao bem. Como causar dano rebaixa e vicia quem o pratica, a conduta verdadeiramente justa não comporta o mal contra ninguém. É o outro lado da recusa platônica ao "bem aos amigos, mal aos inimigos".` },

    { id: 13, tipo: 'verdadeiro-ou-falso', origem: 'professor', categoria: 'revisao', enunciadoHtml: `Para Epicuro, a justiça constitui uma ideia metafísica suprema e imutável que emana da harmonia racional do cosmos, prescindindo de acordos entre os homens.`, correta: false, fonteExtra: false, explicacaoHtml: `Epicuro é lembrado como precursor do contratualismo. Ele não vê a justiça como algo metafísico em si: ela nasce de convenções e pactos de não agressão feitos entre os homens para evitar o dano recíproco.` },

    { id: 14, tipo: 'verdadeiro-ou-falso', origem: 'professor', categoria: 'revisao', enunciadoHtml: `O jurista e filósofo romano Cícero postulava que a gênese e a essência do Direito não devem ser buscadas nas convenções ou decisões humanas contingentes, mas na própria reta razão inerente à Natureza.`, correta: true, fonteExtra: false, explicacaoHtml: `Cícero, sob influência do estoicismo, busca o fundamento do direito na natureza e na razão, e não nas opiniões dos homens. A máxima citada ("Natura juris ab homines repetenda est natura") diz que a essência do Direito deve ser buscada na essência humana.` },

    { id: 15, tipo: 'verdadeiro-ou-falso', origem: 'professor', categoria: 'revisao', enunciadoHtml: `Na Suma Teológica, Santo Tomás de Aquino rompe integralmente com a tipologia aristotélica de justiça por considerá-la inconciliável com os dogmas e ensinamentos das Sagradas Escrituras.`, correta: false, fonteExtra: false, explicacaoHtml: `Tomás não rompe com Aristóteles: retoma a divisão da justiça particular em comutativa e distributiva e a integra à moral cristã do amor ao próximo, sob a virtude da caridade. É a chamada cristianização da justiça clássica.` },

    { id: 16, tipo: 'verdadeiro-ou-falso', origem: 'professor', categoria: 'revisao', enunciadoHtml: `Em sua obra tardia As Leis, Platão passa a valorizar a forma escrita da norma jurídica, interpretando a codificação legal como marco de avanço civilizatório e base do Estado de Direito.`, correta: true, fonteExtra: false, explicacaoHtml: `Nas Leis, obra da maturidade, Platão trata a lei escrita como sinal de progresso e como uma noção primitiva de Estado de Direito, e liga a evolução das sociedades à lei escrita.` },

    { id: 17, tipo: 'verdadeiro-ou-falso', origem: 'professor', categoria: 'revisao', enunciadoHtml: `A distinção romana clássica entre Ius Civile, Ius Gentium e Ius Naturale equiparava integralmente as normas exclusivas da cidade de Roma às regras da razão eterna universais a todos os viventes.`, correta: false, fonteExtra: false, explicacaoHtml: `A tripartição existe justamente para distinguir. O ius civile é o direito próprio de um povo, fundado na vontade do populus. O ius naturale é fundado na razão universal e vale para todos. O ius gentium é o direito comum aos povos. Há leituras diferentes sobre como situar o ius gentium (mais próximo do direito natural ou do direito positivo), mas em nenhuma delas o ius civile se equipara ao natural.` },

    { id: 18, tipo: 'verdadeiro-ou-falso', origem: 'professor', categoria: 'revisao', enunciadoHtml: `Guilherme de Ockham e Duns Escoto representam a transição para a modernidade jurídica ao enfatizarem o primado da vontade individual, da liberdade e a separação metodológica entre a razão empírica e a teologia.`, correta: true, fonteExtra: false, explicacaoHtml: `Escoto e Ockham se contrapõem ao organicismo medieval. Escoto afirma o primado do individual sobre o geral e da liberdade sobre a ordem. Ockham separa o racional do teológico, critica o universalismo da lei natural e fortalece o direito positivo e a noção de direito subjetivo. Por isso preparam a passagem à modernidade.` },

    { id: 19, tipo: 'verdadeiro-ou-falso', origem: 'professor', categoria: 'revisao', enunciadoHtml: `Aristóteles sustenta que a justiça universal (em sentido amplo) reside no acatamento integral das leis da comunidade voltadas à promoção do bem comum.`, correta: true, fonteExtra: false, explicacaoHtml: `Na Ética a Nicômaco, a justiça em sentido amplo, universal ou total, é cumprir as leis que buscam o bem comum. A justiça em sentido estrito, ou particular, trata da distribuição justa entre os indivíduos e se divide em comutativa e distributiva.` },

    { id: 20, tipo: 'verdadeiro-ou-falso', origem: 'professor', categoria: 'revisao', enunciadoHtml: `No pensamento dos sofistas gregos, inexistiam divergências ou relativismos quanto ao valor da moral, sustentando-se a existência de uma justiça cósmica universal imutável vinculada à physis.`, correta: false, fonteExtra: false, explicacaoHtml: `O traço dos sofistas é justamente o ceticismo e o relativismo. Para eles não há justiça em si: a justiça resulta de convenções humanas (nomos), e não de uma ordem natural perene (physis). Além disso, o grupo é heterogêneo, sem uma corrente comum.` }
];
